version: 2

models:
  - name: dim_users
    description: "User dimensions"
  - name: fact_orders
    description: "Order facts"
    columns:
      - name: items
        tests:
          - not_null
    
  - name: dim_products
    description: "Product dimensions"

  - name: int_events_per_session
    description: >
      This model contains the aggregated count of distinct event types for each session using the stg_events model as a source.
    columns:
      - name: session_id
        description: The unique identifier for each session.
        tests:
          - unique
          - not_null
      - name: number_of_*
        description: The count of each distinct event type within a session.
    
